services:
  backend:
    build:
      context: ./maskotas
      dockerfile: Dockerfile
    container_name: maskotas-backend
    env_file:
      - .env.prod
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${RDS_HOST}:5432/${RDS_DB}
      SPRING_DATASOURCE_USERNAME: ${RDS_USER}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
      - maskotas-net

  frontend:
    build:
      context: ./maskotas-frontend
      dockerfile: Dockerfile
    container_name: maskotas-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - maskotas-net

networks:
  maskotas-net:
    driver: bridge
