spring.application.name=maskotas
server.port=8090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://172.27.202.194:5432/maskotas
spring.datasource.username=maskotas
spring.datasource.password=maskotas123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

# Groq AI
# groq.api.key=
